testing curl update command

diff --git a/.github/workflows/java.yml b/.github/workflows/java.yml
--- a/.github/workflows/java.yml
+++ b/.github/workflows/java.yml
@@ -25,26 +25,12 @@ jobs:
     container:
       image: techiescamp/java-agent:3.0.0
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        with:
-          repository: kubernetes-learning-projects/helm-chart
-          token: ${{ secrets.GIT_TOKEN }}
-
-      - name: Check
-        run: ls
-
-      - name: Update Image Tag Values
+      - name: Update Image tag
         run: |
-          chart_dir="nginx"
-          new_image_tag=1.0.${{ github.run_number }}
-          sed -i "s/^\(\s*\)tag: .*/\1tag: $new_image_tag/" "$chart_dir/values.yaml"
-      
-      - name: Commit the changes made
-        run: |
-          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
-          git config --global user.name "${{ secrets.GIT_USERNAME }}"
-          git config --global user.email "${{ secrets.GIT_EMAIL }}"
-          git add .
-          git commit -m "updating image tag 1.0.${{ github.run_number }}"
-          git push origin main
+          curl -X PATCH https://35.165.41.209:30007/api/v1/applications/test \
+          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -d '{
+              "patch": "{\"spec\": {\"source\": {\"repoURL\": \"https://github.com/kubernetes-learning-projects/helm-chart.git\", \"path\": \"nginx\", \"targetRevision\": \"HEAD\", \"parameterOverrides\": [{\"name\": \"nginx.image.tag\", \"value\": \"1.0.${{ github.run_number }}\"}]}}}",
+              "patchType": "merge"
+          }' --insecure && echo "Manifest update successful" || echo "Manifest update failed"
